/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "khoklmuwfwyfhccqbdmf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtob2tsbXV3Znd5ZmhjY3FiZG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1OTMwMzcsImV4cCI6MjA4NTE2OTAzN30.f3gv_g8N4ZUd5d-Zxuef9aEqmnsR70hIbu4RCbQkMTc"
